version: '2'
services:
  latex:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./docs:/workdir
    command: latexmk -pvc main.tex
    user: 1000:1000
    tty: true
    stdin_open: true